# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78e8c8a83475370efd8b0ad39e90e9ef26e0787e867717bc2a916e71ae6ab6fbde268459cc45b909a1f7f33eced1224f3039fe78b58af96cb818292794cc4344

test:
  secret_key_base: 09c3edc287e77a7c8052a7fe2d3530bf63cfa50fa6825daac4a45e8484354c20963ac5e40add8e0e1cfc822c621467329e29822ed63f0eb651b26924bbd7fc09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
